DEBUG = no
FRONT = no
BACK = yes
CC = gcc
ifeq ($(DEBUG),yes)
	CFLAGS = -Wall -W -ansi -pedantic -g -D DEBUG
else
	ifeq ($(DEBUG),yes)
		CFLAGS = -Wall -W -ansi -pedantic -D FRONT
	else
		ifeq ($(BACK),yes)
			CFLAGS = -Wall -W -ansi -pedantic -D BACK
		else
			CFLAGS = -Wall -W -ansi -pedantic
		endif
	endif
endif
LDFLAGS = -lm
EXEC = main

all : $(EXEC)

main :  main.o
	$(CC) -o $@ $^ $(LDFLAGS)

main.o : main.c headers/main.h
	$(CC) -o $@ -c $< $(CFLAGS)

clean:
	rm *.o $(EXEC)
