all: uiMain.c activate.c uiTraces.c uiAnimation.c uiAnonymite.c
		gcc `pkg-config --cflags gtk+-3.0` -o main uiMain.c carte.c rectangle.c point.c activate.c uiTraces.c uiAnimation.c uiAnonymite.c `pkg-config --libs gtk+-3.0`
