all: uiMain.c activate.c uiTraces.c uiAnimation.c uiAnonymite.c fctnCairo.c
		gcc `pkg-config --cflags gtk+-3.0` -o main uiMain.c activate.c uiTraces.c uiAnimation.c uiAnonymite.c fctnCairo.c `pkg-config --libs gtk+-3.0`
